############################################################################        
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: swap_use_percent
    - type: processor_use
    - type: last_boot
    - type: since_last_boot

############################################################################        
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "F"
  value_template: '{{ (value | multiply(0.001) * 1.8 + 32) | round(1) }}'

############################################################################        
- platform: openweathermap
  api_key: 6af01c0de995c5e8302f36820d431309
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - humidity
    - pressure
    - clouds
    - rain
#     - snow

############################################################################        
- platform: miflora
  mac: 'c4:7c:8d:62:d4:99'
  name: Plant (Daddy)
  force_update: false
  monitored_conditions:
    - moisture
    - battery
    - light
    - temperature
    - conductivity

############################################################################        
- platform: template
  sensors:
    battery_level_dome_leak_detector_1:
      friendly_name: 'Dome 1 Battery Level'
      value_template: '{{states.binary_sensor.dome_leak_sensor_liquid_detected.attributes.battery_level}}'
      unit_of_measurement: '%'
    battery_level_smoke_co_alarm_1:
      friendly_name: 'Smoke/CO #1 Alarm Battery'
      value_template: '{{states.zwave.first_alert_zcombo_smoke_and_carbon_monoxide_detector.attributes.battery_level}}'
      unit_of_measurement: '%'
    status_smoke_co_alarm_1:
      friendly_name: 'Smoke/CO #1 Alarm'
      value_template: >-
        {%- if is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "1") %}
           Fire Detected
        {% elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "2") %}
           Carbon Monoxide Detected
        {% elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "12") %}
            Alarm Testing
        {% else %}
            Unknown
        {%- endif %}
    battery_level_smoke_co_alarm_2:
      friendly_name: 'Smoke/CO #2 Alarm Battery'
      value_template: '{{states.zwave.first_alert_zcombo_smoke_and_carbon_monoxide_detector_2.attributes.battery_level}}'
      unit_of_measurement: '%'
    status_smoke_co_alarm_2:
      friendly_name: 'Smoke/CO #2 Alarm'
      value_template: >-
        {%- if is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_2", "13") %}
            Idle
        {% elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_2", "1") %}
            Fire Detected
        {% elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_2", "2") %}
            Carbon Monoxide Detected
        {% elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_2", "12") %}
            Alarm Testing
        {% else %}
            Unknown
        {%- endif %}
    battery_level_smoke_co_alarm_3:
      friendly_name: 'Smoke/CO #3 Alarm Battery'
      value_template: '{{states.zwave.first_alert_zcombo_smoke_and_carbon_monoxide_detector_3.attributes.battery_level}}'
      unit_of_measurement: '%'
    status_smoke_co_alarm_3:
      friendly_name: 'Smoke/CO #3 Alarm'
      value_template: >-
        {%- if is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_3", "13") %}
            Idle
        {% elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_3", "1") %}
            Fire Detected
        {% elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_3", "2") %}
            Carbon Monoxide Detected
        {% elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type_3", "12") %}
            Alarm Testing
        {% else %}
            Unknown
        {%- endif %}
    battery_level_front_door_lock:
      friendly_name: 'Front Door Lock Battery'
      value_template: '{{states.lock.front_door_lock.attributes.battery_level}}'
      unit_of_measurement: '%'
    battery_level_back_door:
      friendly_name: 'Back Door Lock Battery'
      value_template: '{{states.lock.back_door.attributes.battery_level}}'
      unit_of_measurement: '%'

############################################################################        
- platform: mqtt
  state_topic: "spd/cabinet/light"
  name: "Cabinet Light"
 
############################################################################        
- platform: template
  sensors:
    # sensor1_windspeed:
      # friendly_name: Wind Speed
      # unit_of_measurement: 'mi/hr'
      # value_template: >
    washing_machine_watts:
      unit_of_measurement: 'watts'
      value_template: '{{ states.switch.hair_straightener_insight.attributes.current_power_w }}'
      #friendly_name: Washing Machine Power
      #value_template: {{ states.switch.hair_straightener_insight.attributes.current_power_w') }}
      #value_template: {{ states('switch.hair_straightener_insight_current_power_w') }}
      #value_template: '{% if states.switch.hair_straightener_insight %}{{ states.switch.hair_straightener_insight.attributes.current_power_w }}{% else %}Off{% endif %}'
        
############################################################################        
- platform: wunderground
  api_key: 6ac853706bf5f88b
  monitored_conditions:
    - location
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n  
    - temp_high_record_f
    - temp_high_1d_f
    - temp_f
    - temp_low_1d_f
    - temp_low_record_f
    - precip_1d
    - precip_1d_in
    - wind_mph
    - wind_1d_mph
    - alerts
    - station_id
    
############################################################################        
- platform: cert_expiry
  host: !secret cert_expiry_host

  
# - platform: template    
  # sensors:
    # washing_machine_watts:
      # value_template: {{ switch.hair_straightener_insight.state_detail }}
      #friendly_name: Washing Machine Power
      #value_template: {{ states.switch.hair_straightener_insight.attributes.current_power_w') }}
      #value_template: {{ states('switch.hair_straightener_insight_current_power_w') }}
      #value_template: '{% if states.switch.hair_straightener_insight %}{{ states.switch.hair_straightener_insight.attributes.current_power_w }}{% else %}Off{% endif %}'
      



    
        
