#- platform: insteon_local

- name: Stevens-Lamp
  platform: mqtt
  state_topic: /lamp/steven/relay/0
  command_topic: /lamp/steven/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /lamp/steven/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: /lamp/steven/brightness
  brightness_command_topic: /lamp/steven/brightness/set
  rgb_state_topic: /lamp/steven/rgb
  rgb_command_topic: /lamp/steven/rgb/set
  color_temp_command_topic: /lamp/steven/mired/set
  white_value_state_topic: /lamp/steven/channel/3
  white_value_command_topic: /lamp/steven/channel/3/set

- name: Moselles-Lamp
  platform: mqtt
  state_topic: /lamp/moselle/relay/0
  command_topic: /lamp/moselle/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /lamp/moselle/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: /lamp/moselle/brightness
  brightness_command_topic: /lamp/moselle/brightness/set
  rgb_state_topic: /lamp/moselle/rgb
  rgb_command_topic: /lamp/moselle/rgb/set
  color_temp_command_topic: /lamp/moselle/mired/set
  white_value_state_topic: /lamp/moselle/channel/3
  white_value_command_topic: /lamp/moselle/channel/3/set

# - platform: mqtt
  # name: 'Pantry Lights'
  # state_topic: '/lights/pantry/relay/0'
  # command_topic: '/lights/pantry/relay/0'
  # payload_on: 1
  # payload_off: 0
  # rgb_state_topic: '/lights/pantry/color'
  # rgb_command_topic: '/lights/pantry/color'
  # rgb: true
  # optimistic: false
- name: Pantry_Lights
  platform: mqtt
  state_topic: /lights/pantry/relay/0
  command_topic: /lights/pantry/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /lights/pantry/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: /lights/pantry/brightness
  brightness_command_topic: /lights/pantry/brightness/set
  rgb_state_topic: /lights/pantry/rgb
  rgb_command_topic: /lights/pantry/rgb/set
  color_temp_command_topic: /lights/pantry/mired/set
  white_value_state_topic: /lights/pantry/channel/3
  white_value_command_topic: /lights/pantry/channel/3/set

- platform: mqtt
  name: 'Pole Lamp'
  state_topic: '/light/pole/relay/0/set'
  command_topic: '/light/pole/relay/0/set'
  payload_on: 1
  payload_off: 0
  rgb_state_topic: '/light/pole/rgb'
  rgb_command_topic: '/light/pole/rgb/set'
  # rgb: true
  optimistic: false

# - platform: mqtt
#   name: 'Namaste Light'
#   state_topic: 'lamp/namaste/relay/0'
#   command_topic: 'lamp/namaste/relay/0/set'
#   payload_on: 1
#   payload_off: 0
#   rgb_state_topic: 'lamp/namaste/light/color'
#   rgb_command_topic: 'lamp/namaste/color/set'
#   # rgb: true
#   optimistic: false
#   # color_temp: false
#   # color_temp_command_topic: '/lamp/namaste/mired/set'
#   brightness: true
#   brightness_scale: 255
#   brightness_command_topic:  'lamp/namaste/brightness/set'
#   brightness_state_topic: 'lamp/namaste/brightness'
#   white_value: false
#   white_value_command_topic: 'lamp/namaste/channel/3/set'

- platform: mqtt
  name: 'Cabinet Lights 1'
  state_topic: '/lights/cabinet/1/relay/0/set'
  command_topic: '/lights/cabinet/1/relay/0/set'
  payload_on: 1
  payload_off: 0
  white_value_command_topic: '/lights/cabinet/1/channel/3/set'

- platform: mqtt
  name: 'Cabinet Lights 2'
  state_topic: '/lights/cabinet/2/relay/0/set'
  command_topic: '/lights/cabinet/2/relay/0/set'
  payload_on: 1
  payload_off: 0
  white_value_command_topic: '/lights/cabinet/2/channel/3/set'

- name: AddressLight
  platform: mqtt
  state_topic: /light/addressnumber/relay/0
  command_topic: /light/addressnumber/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /light/addressnumber/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: /light/addressnumber/brightness
  brightness_command_topic: /light/addressnumber/brightness/set
  rgb_state_topic: /light/addressnumber/rgb
  rgb_command_topic: /light/addressnumber/rgb/set
  color_temp_command_topic: /light/addressnumber/mired/set
  white_value_state_topic: /light/addressnumber/channel/3
  white_value_command_topic: /light/addressnumber/channel/3/set

- name: BackPorchLight
  platform: mqtt
  state_topic: /light/backporch/relay/0
  command_topic: /light/backporch/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /light/backporch/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: /light/backporch/brightness
  brightness_command_topic: /light/backporch/brightness/set
  rgb_state_topic: /light/backporch/rgb
  rgb_command_topic: /light/backporch/rgb/set
  color_temp_command_topic: /light/backporch/mired/set
  white_value_state_topic: /light/backporch/channel/3
  white_value_command_topic: /light/backporch/channel/3/set


